options:
  logsBucket: gs://wallet-checker/

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'wallet-checker'  # Replace with your function name
      - '--runtime'
      - 'python310'  # Replace with the runtime version you're using
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point'
      - 'runThisThing'  # Replace with your function's entry point
      - '--region'
      - 'us-central1'  # Replace with your preferred region
timeout: '25s'